version: '3.8'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - soc-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - soc-net

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - soc-net

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/log:/var/log
      - ./zeek/logs:/zeek/logs
    depends_on:
      - logstash
    networks:
      - soc-net

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: host
    volumes:
      - ./suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - ./suricata/logs:/var/log/suricata
      - ./pcaps:/pcaps
    command: ["-c", "/etc/suricata/suricata.yaml", "-r", "/pcaps/test.pcap"]
    restart: unless-stopped

  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.3
    container_name: wazuh-manager
    ports:
      - "1514:1514/udp"
      - "1515:1515"
    volumes:
      - ./wazuh/config/ossec.conf:/var/ossec/etc/ossec.conf
    restart: unless-stopped
    networks:
      - soc-net

  zeek:
    image: blacktop/zeek:latest
    container_name: zeek
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./zeek/logs:/usr/local/zeek/logs
      - ./zeek/scripts:/usr/local/zeek/share/zeek/site
      - ./pcaps:/pcaps
    command: ["zeek", "/pcaps/test.pcap"]
    restart: unless-stopped

volumes:
  esdata:

networks:
  soc-net:
    driver: bridge
