name: CI - Cybersecurity Projects

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main

      - name: Validate Sigma rules
        run: |
          pip install sigma
          sigma tools validate rules/
